apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: semaphore-manual
  namespace: semaphore
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    ingress.cilium.io/backend-protocol: "http"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - semaphore.avgmax.team
    secretName: semaphore-tls
  rules:
  - host: semaphore.avgmax.team
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: semaphore
            port:
              number: 3000