apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - zitadel/namespace.yaml
  # - zitadel/release.yaml
  - teleport/namespace.yaml
  - teleport/release.yaml
  - teleport/ingress.yaml
  - semaphore/namespace.yaml
  - semaphore/release.yaml
  - semaphore/ingress.yaml
  - tofu-controller/release.yaml