apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/namespace.yaml
  - cert-manager/release.yaml
  - cilium/release.yaml
  - cilium/ingress.yaml
  # - cilium/pool.yaml # LoadBalancer 사용 시
  - sources/helm-repositories.yaml
  - tetragon/namespace.yaml
  - tetragon/release.yaml
