apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teleport-ingress
  namespace: teleport
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "cilium"
    ingress.cilium.io/backend-protocol: "https"
    ingress.cilium.io/tls-passthrough: "true"
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - teleport.avgmax.team
        - "*.teleport.avgmax.team"
      secretName: teleport-tls-all
  rules:
    - host: teleport.avgmax.team
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teleport-teleport-cluster
                port:
                  number: 443
    - host: "*.teleport.avgmax.team"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teleport-teleport-cluster
                port:
                  number: 443